language: python
python:
  - "2.7"
compiler:
  - gcc
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev libboost-dev
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make test
  - tests/test_arf
  - python setup.py test