language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
compiler:
  - gcc
  - clang
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libhdf5-serial-dev libboost-dev
install:
  - pip install numpy==1.8.0 --use-mirrors
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script:
  - make test
  - tests/test_arf
  - python setup.py test
