language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
compiler:
  - clang
  - gcc
# command to install dependencies
install:
  - sudo apt-get install hdf5-dev
  - pip install -r requirements.txt
# command to run tests
script:
  - make test
  - tests/test_arf
  - python setup.py test